name: CICD

on:
  workflow_dispatch:
    inputs:
      workflow_type:
        description: 'workflow type'
        required: true
        type: choice
        options:
        - 'pull_request'
        - 'main'

jobs:
  cd:

    runs-on: ubuntu-latest
    env:
      IS_PRERELEASE: ${{ workflow_type == 'pull_request' }}  
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
    
      - name: Print vars
        run: echo $IS_PRERELEASE
      
      - name: Checkout
      - uses: actions/checkout@v3.3.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Bump version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ secrets.APP_VERSION }}
          version-fragment: ${{ steps.version_type.outputs.value }}
      
      - name: Print Version
        run: echo ${{ steps.bump_version.outputs.next-version }}
      
      - name: Add tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ secrets.APP_VERSION }}
      
      - name: Create a Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ secrets.APP_VERSION }}
          prerelease: $IS_PRERELEASE
          title: "Release version: ${{ secrets.APP_VERSION }}"

      - name: Dotnet Pack
        shell: bash
        run: |
          dotnet pack /p:Version=${{ steps.bump_version.outputs.next-version }} --configuration=Release --output=./packages \
          /p:NoWarn=NU5105 \
          /p:RepositoryUrl=https://github.com/Nairda015/gh-actions-tests \
          /p:RepositoryType=git
          
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: packages
          name: nuget-packages
