name: milti-job-print

on:
  push:
    branches: [ main ]

env:
  MY_VAR: "value"
 

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      myvar1: ${{ steps.step1.outputs.MY_VAR3 }}
      myvar2: ${{ steps.step2.outputs.MY_VAR4 }}
    steps:
  
    - name: Access the global environment variable
      id: step1
      run: echo "MY_VAR is set to ${{ env.MY_VAR }}"
      
    - run: echo "MY_VAR=value2" >> $GITHUB_ENV
    
    - run: echo "MY_VAR3=green" >> $GITHUB_OUTPUT
    - run: echo "MY_VAR4=red" >> $GITHUB_OUTPUT
      
   
    - run: echo "MY_VAR2=value3" >> $GITHUB_ENV
      id: step2

  job2:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    steps:
    - name: Access the global environment variable
      run: echo "MY_VAR is set to ${{ env.MY_VAR }}"
      
    - run: echo ${{needs.job1.outputs.myvar1}} ${{needs.job1.outputs.myvar2}}  
