name: milti-job-print

on:
  push:
    branches: [ main ]

env:
  globalEnv: 123
 

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      stageEnv: ${{ steps.init.outputs.stageEnv }}
    steps:       
      - name: Make environment variables global 
        id: init
        run: echo "stageEnv=456" >> $GITHUB_OUTPUT
      - run: echo ${{ env.stageEnv }}
      
      - run: echo "globalEnv=456" >> $GITHUB_OUTPUT
      - run: echo ${{ env.globalEnv }}
      
      - run: echo "stageEnv=456" >> $GITHUB_ENV
      - run: echo ${{ env.stageEnv }}
      

  job2:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    steps:
      
    - run: echo ${{ needs.job1.outputs.stageEnv }}
    - run: echo ${{ env.globalEnv }}
