name: print

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      custom_version:
        required: true
        default: 'bug'
        type: choice
        options:
        - 'feature'
        - 'bug'
        - 'major'
  
jobs:
  print:
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.custom_version.outputs.version }}
    
    steps:
          
      - name: Set color
        id: get_version
        run: echo "VERSION=major" >> $GITHUB_OUTPUT
        
      - name: Get color
        run: echo "The selected color is ${{ steps.get_version.outputs.VERSION }}"
          
      
      - run: echo ${{ steps.get_version.outputs.VERSION }}
      
      
      
      
