name: print

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      custom_version:
        required: true
        default: 'bug'
        type: choice
        options:
        - 'feature'
        - 'bug'
        - 'major'
  
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
          
      - name: get version
        id: get_version
        shell: bash
        run: |
          echo ${{ github.event.inputs.custom_version }}
          if [[ ${{ github.event.inputs.custom_version }} = "" ]]; then
            echo "VERSION=bug" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.event.inputs.custom_version }}" >> $GITHUB_OUTPUT
          fi  
        
      - run: echo ${{ steps.get_version.outputs.VERSION }}
      
      
      
      
