name: print

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      custom_version:
        required: true
        default: 'bug'
        type: choice
        options:
        - 'feature'
        - 'bug'
        - 'major'
        - 'minor'      
      is_prerelease:
        required: true
        default: false
        type: boolean
  
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
          
      - name: override
        if: ${{ github.event.inputs.custom_version == '' }}
        run: echo "VERSION=feature" >> $GITHUB_ENV
        
      - run: echo ${{ env.VERSION }}
        
      - name: override bool
        if: ${{ github.event.inputs.custom_version == '' }}
        run: echo "is_prerelease=feature" >> $GITHUB_ENV

      - run: echo ${{ env.is_prerelease }}
      
      
      
      
