name: print

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      custom_version:
        required: true
        default: 'bug'
        type: choice
        options:
        - 'feature'
        - 'bug'
        - 'major'
        - 'minor'      
      is_prerelease:
        required: true
        default: false
        type: boolean
  
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
          
      - name: override custom_version
        if: ${{ github.event.inputs.custom_version == '' }}
        run: echo "VERSION=feature" >> $GITHUB_ENV
        
      - run: echo ${{ env.VERSION }}
        
      - name: print is_prerelease
        run: echo ${{ github.event.inputs.is_prerelease }}  
      
      - name: override is_prerelease
        if: ${{ github.event.inputs.is_prerelease == '' }}
        run: echo "IS_PRERELEASE=false" >> $GITHUB_ENV

      - run: echo ${{ env.IS_PRERELEASE }}
      
      
      
      
